name: Frontend Deploy

on:
  push:
    branches: [ master ] #master로 push되었을 때 실행

jobs:
  frontend:
    name: CI with Node
    runs-on: ubuntu-latest
    env:
      working-directory: ./Front

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
    
      - name: Check Node V #virtual 환경에 node 이미 설치되어 있음. yarn, npm, AWS CLI도 마찬가지
        run: node -v

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }} 
          restore-keys: #일치하는 캐시 key가 없을 때 차선택으로 캐싱폴더를 찾는다.
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }} #Front 폴더 하위에 생성
        
      - name: Configure AWS credentials #사용자 인증
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
        run:
          aws s3 cp --recursive --region ap-northeast-2 build s3://too-good-to-go #파일이 아닌 폴더 업로드 시에 --recursive 필수
        working-directory: ${{ env.working-directory }}

      - name: build result to slack #슬랙 메시지 출력
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Frontend CI/CD
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
